// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxZI-YaJEvN_Kr0n4b8BQyKBCMbknZZQw',
    appId: '1:279146522782:web:3ad4b348decd02aec1f38f',
    messagingSenderId: '279146522782',
    projectId: 'child-safe-bus-tracker',
    authDomain: 'child-safe-bus-tracker.firebaseapp.com',
    storageBucket: 'child-safe-bus-tracker.firebasestorage.app',
    measurementId: 'G-094CGYN4ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzWBJ04NXz1Fr8lZqq1mVUjnys6sn9mIU',
    appId: '1:279146522782:android:90acffa2bd8288afc1f38f',
    messagingSenderId: '279146522782',
    projectId: 'child-safe-bus-tracker',
    storageBucket: 'child-safe-bus-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCYBnrQxKFjRiEtud9pV6d0Frm8oN-mEY',
    appId: '1:279146522782:ios:6407acc8890be76dc1f38f',
    messagingSenderId: '279146522782',
    projectId: 'child-safe-bus-tracker',
    storageBucket: 'child-safe-bus-tracker.firebasestorage.app',
    iosBundleId: 'com.example.childsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCYBnrQxKFjRiEtud9pV6d0Frm8oN-mEY',
    appId: '1:279146522782:ios:6407acc8890be76dc1f38f',
    messagingSenderId: '279146522782',
    projectId: 'child-safe-bus-tracker',
    storageBucket: 'child-safe-bus-tracker.firebasestorage.app',
    iosBundleId: 'com.example.childsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxZI-YaJEvN_Kr0n4b8BQyKBCMbknZZQw',
    appId: '1:279146522782:web:135c08d587dad879c1f38f',
    messagingSenderId: '279146522782',
    projectId: 'child-safe-bus-tracker',
    authDomain: 'child-safe-bus-tracker.firebaseapp.com',
    storageBucket: 'child-safe-bus-tracker.firebasestorage.app',
    measurementId: 'G-93X724TBG7',
  );

}