import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart'; // <-- ADDED FOR OFFLINE SUPPORT
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'login_screen.dart';
import 'driver_screen.dart';
import 'parent_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // --- ENABLE FIRESTORE OFFLINE PERSISTENCE ---
  // This allows the Driver app to cache attendance checks in dead zones
  // and sync them automatically when the internet reconnects!
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Child Safe',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.indigo, useMaterial3: true),
      home: const LoginScreen(),
    );
  }
}

// --- HOMESCREEN CONTROLLER ---
class HomeScreen extends StatelessWidget {
  final String userRole;
  final String schoolId;

  const HomeScreen({super.key, required this.userRole, required this.schoolId});

  @override
  Widget build(BuildContext context) {
    if (userRole == 'driver') {
      return DriverScreen(schoolId: schoolId);
    } else {
      return ParentScreen(schoolId: schoolId);
    }
  }
}
